### ISSUE TITLE
Show total # of repos?

### ISSUE THREAD

**Issue by neelsmith** [ryanfb/ogl-browser#4]
As long as we're being greedy and asking for display tweaks...

it might be helpful for people as they're playing with and sorting results to see a convenient total number of repositories?

**Comment by neelsmith** [comment]
If anyone asks you why you bothered to do this, I can tell you one user 
is very happy with this enhancement!

Thanks!

**Comment by ryanfb** [comment]
No problem! Just pushed a slight fix that should use the number of repositories which matched the OCR regex (i.e. repos that show in the list) rather than total number of repos in the organization.
